name: Build & Sign APK with Apktool

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write   # Needed for GitHub Releases

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Install Apktool
      run: |
        wget https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool
        wget https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.9.3.jar -O apktool.jar
        chmod +x apktool
        sudo mv apktool apktool.jar /usr/local/bin/
        echo 'java -jar /usr/local/bin/apktool.jar "$@"' | sudo tee /usr/local/bin/apktool-cli
        sudo chmod +x /usr/local/bin/apktool-cli

    - name: Build unsigned APK
      run: |
        apktool-cli b . -o build/myapp_unsigned.apk

    - name: Decode Keystore
      run: echo "${{ secrets.KEYSTORE_FILE }}" | tr -d '\n\r' | base64 -d > mykey.keystore

    - name: Zipalign APK
      run: |
        $ANDROID_HOME/build-tools/34.0.0/zipalign -p -f 4 build/myapp_unsigned.apk build/myapp_aligned.apk

    - name: Sign APK
      run: |
        $ANDROID_HOME/build-tools/34.0.0/apksigner sign \
          --ks mykey.keystore \
          --ks-pass pass:${{ secrets.KEYSTORE_PASS }} \
          --key-pass pass:${{ secrets.KEY_PASS }} \
          --ks-key-alias ${{ secrets.KEY_ALIAS }} \
          --out build/myapp_signed.apk build/myapp_aligned.apk

    - name: Verify Signature & Alignment
      run: |
        $ANDROID_HOME/build-tools/34.0.0/zipalign -c -v 4 build/myapp_signed.apk
        $ANDROID_HOME/build-tools/34.0.0/apksigner verify build/myapp_signed.apk

    - name: Upload signed APK as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: myapp-signed
        path: build/myapp_signed.apk

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.run_number }}
        name: "Release v${{ github.run_number }}"
        body: "Automated signed APK build from Apktool workflow"
        files: build/myapp_signed.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
